export const GET_PLAYLIST_REQUEST = 'GET_PLAYLIST_REQUEST';
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR';
export const GET_NEXT_SONG_REQUEST ='GET_NEXT_SONG_REQUEST';
export const GET_NEXT_SONG_SUCCESS ='GET_NEXT_SONG_SUCCESS';
export const GET_NEXT_SONG_ERROR ='GET_NEXT_SONG_ERROR';
export const UPDATE_PLAYLIST_REQUEST = 'UPDATE_PLAYLIST_REQUEST';
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_ERROR = 'UPDATE_PLAYLIST_ERROR';
export const LIKE_SONG_REQUEST = 'LIKE_SONG_REQUEST';
export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS' ;
export const LIKE_SONG_ERROR = 'LIKE_SONG_ERROR' ;
export const DISLIKE_SONG_REQUEST = 'DISLIKE_SONG_REQUEST';
export const DISLIKE_SONG_SUCCESS = 'DISLIKE_SONG_SUCCESS' ;
export const DISLIKE_SONG_ERROR = 'DISLIKE_SONG_ERROR' ;

